spring.application.name=proyectofinal

# ---------- H2 persistente en archivo ----------
spring.datasource.url=jdbc:h2:file:./data/proyectofinaldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ---------- JPA ----------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ---------- Consola H2 ----------
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ---------- JSON responses ----------
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.indent_output=true

# ---------- JWT ----------
jwt.expiry=30
jwt.secret=MiClaveSecretaSuperSeguraParaJWT2026EnProgramacionAvanzadaUniquindio

# ---------- Seed de usuarios de seguridad ----------
default-users.users[0].username=admin@solicitudes.com
default-users.users[0].password=admin123
default-users.users[0].role=ADMIN
default-users.users[1].username=agente@solicitudes.com
default-users.users[1].password=agente123
default-users.users[1].role=USER
