-- Limpieza para repetir pruebas
DELETE FROM SOLICITUDES;
DELETE FROM USUARIOS;

-- Usuarios base
INSERT INTO USUARIOS (ID, NOMBRE, EMAIL, ROL_USER) VALUES ('U001', 'Ana Torres', 'ana1@demo.com', 'ESTUDIANTE');
INSERT INTO USUARIOS (ID, NOMBRE, EMAIL, ROL_USER) VALUES ('U002', 'Carlos Ruiz', 'carlos1@demo.com', 'DOCENTE');
INSERT INTO USUARIOS (ID, NOMBRE, EMAIL, ROL_USER) VALUES ('U003', 'Maria Perez', 'maria1@demo.com', 'ESTUDIANTE');

-- Solicitudes para pruebas de la guia 11
INSERT INTO SOLICITUDES (
    ID, CODIGO, DESCRIPCION, ESTADO, SOLICITANTE_ID, RESPONSABLE_ID, PRIORIDAD, TIPO,
    FECHA_CREACION, FECHA_MODIFICACION, FECHA_CIERRE
) VALUES
('S001', 'SOL-0001', 'Homologacion por traslado', 'CLASIFICADA', 'U001', 'U002', 'CRITICA', 'HOMOLOGACION', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL),
('S002', 'SOL-0002', 'Soporte campus virtual', 'ASIGNADA', 'U001', 'U002', 'ALTA', 'SOPORTE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL),
('S003', 'SOL-0003', 'Homologacion plan antiguo', 'CREADA', 'U003', NULL, 'MEDIA', 'HOMOLOGACION', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL),
('S004', 'SOL-0004', 'Certificado de notas', 'CERRADA', 'U003', 'U002', 'BAJA', 'CERTIFICADO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('S005', 'SOL-0005', 'Homologacion electivas', 'ASIGNADA', 'U001', 'U002', 'ALTA', 'HOMOLOGACION', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL);
